import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000';
const nav = [['Overview','grid'],['Inventory','car'],['Leads','users'],['Appointments','calendar'],['Customer History','history']];
const endpoints = {Inventory:'/api/admin/inventory',Leads:'/api/admin/leads',Appointments:'/api/admin/appointments'};
const columns = {Inventory:['vehicle_id','vehicle','condition','sale_price','vehicle_status','dealership_location'],Leads:['lead_id','customer_id','lead_status','budget','lead_score','lead_temperature','assigned_salesperson'],Appointments:['appointment_id','customer_id','vehicle_id','appointment_date','appointment_time','appointment_type','status']};

function Icon({name}) { const paths={grid:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z',car:'M5 17h14l-1-6-2-4H8l-2 4-1 6Zm2-6h10M7 17v2M17 17v2',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',calendar:'M3 5h18v16H3zM16 3v4M8 3v4M3 10h18',history:'M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5M12 7v5l3 2'}; return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]}/></svg>; }
function Badge({value}) { const tone=String(value||'').toLowerCase().replaceAll(' ','-'); return <span className={`badge ${tone}`}>{value||'—'}</span>; }
function money(value) { return value==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value); }
function display(row,key) { if(key==='vehicle')return <><strong>{row.year} {row.make} {row.model}</strong><small>{row.trim}</small></>; if(key==='sale_price'||key==='budget')return money(row[key]); if(key.includes('status')||key.includes('temperature')||key==='condition')return <Badge value={row[key]}/>; return row[key]??'—'; }

function Overview({summary,go}) { const cards=[['Total inventory',summary.vehicles,'Across the dealership group','car'],['Available now',summary.available_vehicles,'Ready for customer discovery','grid'],['CRM leads',summary.leads,`${summary.hot_leads||0} high-intent buyers`,'users'],['Appointments',summary.appointments,`${summary.confirmed_appointments||0} confirmed`,'calendar']]; return <><div className="hero"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>Dealership intelligence,<br/>grounded in real records.</h2><p>One connected view of inventory, customer intent and showroom activity across NexDrive Motors.</p></div><div className="hero-mark"><span>N</span><small>PLANO · TEXAS</small></div></div><div className="metrics">{cards.map(([label,value,note,icon])=><article key={label}><div className="metric-icon"><Icon name={icon}/></div><span>{label}</span><strong>{Number(value||0).toLocaleString()}</strong><small>{note}</small></article>)}</div><div className="overview-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">SYSTEM STATUS</span><h3>Production workflow</h3></div><Badge value="All systems operational"/></div><div className="workflow"><div><b>01</b><span><strong>Inventory grounded</strong><small>10,000 verified records</small></span></div><div><b>02</b><span><strong>Customer qualified</strong><small>Deterministic lead scoring</small></span></div><div><b>03</b><span><strong>Outcome traced</strong><small>Bookings stored in Supabase</small></span></div></div></section><section className="panel quick"><span className="eyebrow">QUICK ACCESS</span><h3>Explore live operations</h3><button onClick={()=>go('Inventory')}>Browse inventory <span>→</span></button><button onClick={()=>go('Leads')}>Review CRM pipeline <span>→</span></button><button onClick={()=>go('Appointments')}>View showroom schedule <span>→</span></button></section></div></>; }

function App() {
 const [view,setView]=useState('Overview'),[rows,setRows]=useState([]),[summary,setSummary]=useState({}),[state,setState]=useState('loading'),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[customer,setCustomer]=useState('CUST-004306'),[history,setHistory]=useState(null),[selected,setSelected]=useState(null);
 const load=async()=>{setState('loading');setSelected(null);try{if(view==='Overview'){const r=await fetch(`${API}/api/admin/summary`);if(!r.ok)throw Error();setSummary(await r.json())}else if(view==='Customer History'){const r=await fetch(`${API}/api/tools/get-customer-history/${customer}`);if(!r.ok)throw Error();setHistory((await r.json()).history)}else{const p=new URLSearchParams({limit:'50'});if(query&&view==='Inventory')p.set('q',query);if(status)p.set('status',status);const r=await fetch(`${API}${endpoints[view]}?${p}`);if(!r.ok)throw Error();setRows((await r.json()).records)}setState('ready')}catch{setState('error')}};
 useEffect(()=>{const path=view==='Overview'?'/api/admin/summary':view==='Customer History'?'/api/tools/get-customer-history/CUST-004306':endpoints[view]+'?limit=50';fetch(API+path).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(view==='Overview')setSummary(d);else if(view==='Customer History')setHistory(d.history);else setRows(d.records);setState('ready')}).catch(()=>setState('error'))},[view]);
 const resultText=useMemo(()=>`${rows.length} records`,[rows]); const switchView=next=>{setView(next);setState('loading');setStatus('');setQuery('');setSelected(null)};
 return <div className="app-shell"><aside><div className="brand"><div className="logo">N</div><div><strong>NEXDRIVE</strong><span>MOTORS</span></div></div><div className="location"><i></i><div><small>FLAGSHIP LOCATION</small><strong>Plano, Texas</strong></div></div><nav>{nav.map(([label,icon])=><button className={view===label?'active':''} onClick={()=>switchView(label)} key={label}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="side-foot"><i></i><div><strong>AI Agent Online</strong><small>8 tools connected</small></div></div></aside><main><header><div><span className="eyebrow">NEXDRIVE OPERATIONS</span><h1>{view==='Overview'?'Command Center':view}</h1></div><div className="header-right"><div className="live"><i></i> Live Supabase</div><div className="avatar">NE</div></div></header>
 {view==='Overview'&&state==='ready'&&<Overview summary={summary} go={switchView}/>} {view!=='Overview'&&<><section className="toolbar"><div className="search"><span>⌕</span><input value={view==='Customer History'?customer:query} onChange={e=>view==='Customer History'?setCustomer(e.target.value):setQuery(e.target.value)} placeholder={view==='Customer History'?'Enter customer ID':'Search inventory records'}/></div>{view!=='Customer History'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{(view==='Inventory'?['Available','Reserved','Sold','Pending Sale']:view==='Leads'?['New','Qualified','Test Drive','Won','Lost']:['Requested','Confirmed','Completed','Cancelled']).map(x=><option key={x}>{x}</option>)}</select>}<button className="primary" onClick={load}>Refresh data</button></section><div className="result-bar"><span>{view==='Customer History'?'Authoritative CRM profile':resultText}</span><small>Updated from production database</small></div></>}
 {state==='loading'&&<div className="state-card"><div className="loader"></div><h3>Loading live records</h3><p>Connecting to the NexDrive data platform…</p></div>}{state==='error'&&<div className="state-card error"><b>!</b><h3>We couldn't load this view</h3><p>Check the API connection and try again.</p><button onClick={load}>Try again</button></div>}
 {state==='ready'&&view!=='Overview'&&view!=='Customer History'&&(rows.length?<div className="table-card"><table><thead><tr>{columns[view].map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} onClick={()=>setSelected(row)}>{columns[view].map(c=><td key={c}>{display(row,c)}</td>)}</tr>)}</tbody></table></div>:<div className="state-card"><h3>No matching records</h3><p>Adjust the search or status filter.</p></div>)}
 {state==='ready'&&view==='Customer History'&&history&&<div className="customer-layout"><section className="profile-card"><div className="profile-top"><div className="profile-avatar">{history.customer.first_name?.[0]}{history.customer.last_name?.[0]}</div><div><Badge value={history.customer.buyer_profile}/><h2>{history.customer.first_name} {history.customer.last_name}</h2><p>{history.customer.customer_id} · {history.customer.city}, {history.customer.state}</p></div></div><div className="profile-grid"><div><small>PREFERRED VEHICLE</small><strong>{history.customer.preferred_brand} {history.customer.preferred_vehicle_type}</strong></div><div><small>BUDGET RANGE</small><strong>{money(history.customer.budget_min)} – {money(history.customer.budget_max)}</strong></div><div><small>PURCHASE TIMELINE</small><strong>{history.customer.purchase_timeline}</strong></div><div><small>FAMILY SIZE</small><strong>{history.customer.family_size} people</strong></div></div></section><section className="timeline-card"><span className="eyebrow">CRM TIMELINE</span><h3>Customer activity</h3>{[...history.leads.map(x=>({title:`Lead ${x.lead_status}`,meta:`Score ${x.lead_score} · ${x.lead_temperature}`,date:x.created_at})),...history.appointments.map(x=>({title:x.appointment_type,meta:`${x.status} · ${x.vehicle_id}`,date:x.appointment_date}))].slice(0,6).map((x,i)=><div className="timeline-row" key={i}><i></i><div><strong>{x.title}</strong><small>{x.meta}</small></div><time>{String(x.date||'').slice(0,10)}</time></div>)}</section></div>}</main>
 {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">RECORD DETAIL</span><h2>{selected.vehicle_id||selected.lead_id||selected.appointment_id}</h2><div className="drawer-list">{Object.entries(selected).map(([k,v])=><div key={k}><small>{k.replaceAll('_',' ')}</small><strong>{k==='sale_price'||k==='budget'?money(v):String(v??'—')}</strong></div>)}</div></section></div>}</div>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
