-- Per-vehicle Supabase Storage image metadata. Run after 01-12.

BEGIN;

-- Migration 11 stored licensed make/model representative URLs in a table with
-- this name. Preserve those records before introducing per-vehicle metadata.
DO $$
BEGIN
    IF to_regclass('public.vehicle_model_images') IS NULL
       AND EXISTS (
           SELECT 1
           FROM information_schema.columns
           WHERE table_schema = 'public'
             AND table_name = 'vehicle_images'
             AND column_name = 'image_key'
       ) THEN
        ALTER TABLE public.vehicle_images RENAME TO vehicle_model_images;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.vehicle_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT vehicle_storage_images_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_storage_images_vehicle_fk
        FOREIGN KEY (vehicle_id)
        REFERENCES public.vehicles(vehicle_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT vehicle_storage_images_path_uniq UNIQUE (storage_path),
    CONSTRAINT vehicle_storage_images_order_uniq UNIQUE (vehicle_id, sort_order),
    CONSTRAINT vehicle_storage_images_order_chk CHECK (sort_order >= 0),
    CONSTRAINT vehicle_storage_images_path_chk CHECK (
        storage_path ~ (
            '^vehicles/' || vehicle_id
            || '/[A-Za-z0-9][A-Za-z0-9._/-]*\.(webp|jpg|jpeg|png|avif)$'
        )
        AND storage_path !~ '(^|/)\.\.(/|$)'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_vehicle_storage_images_one_primary
    ON public.vehicle_images (vehicle_id)
    WHERE is_primary;

CREATE INDEX IF NOT EXISTS idx_vehicle_storage_images_ordered
    ON public.vehicle_images (vehicle_id, is_primary DESC, sort_order ASC, id ASC);

ALTER TABLE public.vehicle_images ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vehicle_images FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.vehicle_images_id_seq FROM anon, authenticated;
GRANT ALL ON public.vehicle_images TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vehicle_images_id_seq TO service_role;

COMMIT;
